# Generated by Django 5.0.6 on 2024-05-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkty',
            old_name='reservation',
            new_name='rezerwacja',
        ),
        migrations.RemoveField(
            model_name='produkty',
            name='model',
        ),
    ]
