# Generated by Django 5.0.6 on 2024-05-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0002_rename_reservation_produkty_rezerwacja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='rezerwacja',
        ),
    ]
