# Generated by Django 5.0.6 on 2024-05-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0004_produkty_cena_produkty_marka_produkty_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, null=True)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.AlterModelOptions(
            name='produkty',
            options={'verbose_name': ('Produkt',), 'verbose_name_plural': 'Produkty'},
        ),
    ]
