# Generated by Django 5.0.6 on 2024-05-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0005_marka_alter_produkty_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marka',
            old_name='model',
            new_name='marka',
        ),
    ]
