# Generated by Django 5.0.6 on 2024-05-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0007_remove_produkty_marka_produkty_producent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkty',
            old_name='producent',
            new_name='marka',
        ),
    ]
