# Generated by Django 5.0.6 on 2024-05-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0008_rename_producent_produkty_marka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkty',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
    ]
