# Generated by Django 5.0.3 on 2024-06-05 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0010_kategoria_produkty_kategoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaKoszyka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('koszyk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produkty.koszyk')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produkty.produkty')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produkty.produkty')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='Produkty.zamowienie')),
            ],
        ),
    ]
